### PR TITLE
Python 2.7: dummy commit to trigger wheel builds

### PR DESCRIPTION
**Pull request by grlee77**

### CODE REVIEW

**Comment by grlee77** [comment]
@hgomersall 
I made this branch just to get wheels for 2.7, but apparently Travis-CI is not configured to build these branch and I don't seem to have permissions there to add it. 
**edit**: you can see where it tried and failed to get permission here: https://travis-ci.org/pyFFTW/pyFFTW-wheels/requests

**Comment by hgomersall** [comment]
Do you need access to Travis for this?

**Comment by grlee77** [comment]
I think so. At least, it didn't seem that I had permissions for it on my account (I have the same username there)

**Comment by hgomersall** [comment]
I don't think it's a permissions issue, I think it needs to be set here:
https://github.com/pyFFTW/pyFFTW-wheels/blob/cd891f0a167cc9898f3a4cacb09aa2b97bf576a3/.travis.yml#L79

**Comment by hgomersall** [comment]
Docs: https://docs.travis-ci.com/user/customizing-the-build/#building-specific-branches

**Comment by grlee77** [comment]
Great, thanks! I guess I have only ever used Travis on a master branch and never paid attention to that section. It seems to be working now.

**Pull request merged**
